services:

  localstack:
    container_name: "aws-dealership"
    image: localstack/localstack-pro:4.0.3
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (Pro)
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - NEPTUNE_USE_SSL=1
      - PERSISTENCE=1
      - ECS_REMOVE_CONTAINERS=0
    volumes:
      - "./localstack/localstack-init.sh:/etc/localstack/init/ready.d/localstack-init.sh"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - dealership-network
volumes:
  cache:
    driver: local

networks:
  dealership-network:
    driver: bridge